global:
  scrape_interval: 15s
  external_labels:
    monitor: 'test-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.32:9090']