apiVersion: v1
kind: Pod
metadata:
  name: dcgm-pod
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.0.0-rc.12"
spec:
  containers:
  - image: "nvidia/dcgm-exporter:1.7.2"
    env:
    - name: "DCGM_EXPORTER_LISTEN"
      value: ":9400"
    - name: "DCGM_EXPORTER_KUBERNETES"
      value: "true"
    name: "dcgm-exporter"
    ports:
    - name: "metrics"
      containerPort: 9400
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    volumeMounts:
    - name: "pod-gpu-resources"
      readOnly: true
      mountPath: "/var/lib/kubelet/pod-resources"
  volumes:
  - name: "pod-gpu-resources"
    hostPath:
      path: "/var/lib/kubelet/pod-resources"
      
---

kind: Service
apiVersion: v1
metadata:
  name: "dcgm-exporter"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.0.0-rc.12"
spec:
  selector:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.0.0-rc.12"
  ports:
  - name: "metrics"
    port: 9400
      
      