kind: Service
apiVersion: v1
metadata:
  name: "dcgm"
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.0.0-rc.12"
spec:
  selector:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "2.0.0-rc.12"
  ports:
  - name: "metrics"
    port: 9400
