{{- if .Values.dcgmExporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.dcgmExporter.fullname" . }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.dcgmExporter.service.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.dcgmExporter.port.containerPort }}
  selector:
    {{- include "prometheus.dcgmExporter.matchLabels" . | nindent 4 }}
  type: {{ .Values.dcgmExporter.port.type }}
{{- end -}}
