apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: testvolume
      mountPath: /data/shared
  - name: nginx
    image: nginx
    volumeMounts:
    - name: testvolume
      mountPath: /data/shared
  volumes:
  - name: testvolume
    hostPath:
      path: /root/son/Development/kubernetes/volumes
      type: Directory
   